DROP FUNCTION IF EXISTS CHINSELL.VerificarEmail;
GO
DROP FUNCTION IF EXISTS CHINSELL.VerificarPass;
GO
DROP FUNCTION IF EXISTS CHINSELL.VerificarID;
GO
DROP FUNCTION IF EXISTS CHINSELL.VerificarTitulo;
GO
CREATE FUNCTION CHINSELL.VerificarEmail(@Email varchar(30)) RETURNS INT
AS
	BEGIN
		DECLARE @count	INT
		SELECT @count=COUNT(1) FROM CHINSELL.UTILIZADOR WHERE Email=@Email
		RETURN @COUNT
	END
GO

CREATE FUNCTION CHINSELL.VerificarPass(@Pass varchar(30)) RETURNS INT
AS
	BEGIN
		DECLARE @count	INT
		SELECT @count=COUNT(1) FROM CHINSELL.UTILIZADOR WHERE Pass=@Pass
		RETURN @COUNT
	END
GO

CREATE FUNCTION CHINSELL.VerificarID(@id int) RETURNS INT
AS
	BEGIN
		DECLARE @count	INT
		SELECT @count=COUNT(1) FROM CHINSELL.COMPRA WHERE id=@id
		RETURN @COUNT
	END
GO

CREATE FUNCTION CHINSELL.VerificarTitulo(@Título varchar(20)) RETURNS INT
AS
	BEGIN
		DECLARE @count	INT
		SELECT @count=COUNT(1) FROM CHINSELL.PRODUTO WHERE Título=@Título
		RETURN @COUNT
	END
GO